### PR TITLE
Files/archive

### PR DESCRIPTION
**Pull request by CostinCarabas**
Versiune finală la arhive.

### CODE REVIEW

**Comment by Sergiu121** [comment]
Published at http://sergiu121.github.io/refs/pull/18/merge

**Comment by Sergiu121** [comment]
Published at http://sergiu121.github.io/refs/pull/18/merge

**Comment by Sergiu121** [comment]
Published at http://sergiu121.github.io/refs/pull/18/merge

**Comment by CostinCarabas** [comment]
Voi continua în PR #14

**Pull request closed without merging**
