### PR TITLE
Toggle sidebar chapters sections

### PR DESCRIPTION
**Pull request by edi33416**
Signed-off-by: Eduard Staniloiu <edi33416@gmail.com>

### CODE REVIEW

**Comment by Sergiu121** [comment]
Published at http://sergiu121.github.io/refs/pull/15/merge

**Comment by Sergiu121** [comment]
Published at http://sergiu121.github.io/refs/pull/15/merge

**Comment by Sergiu121** [comment]
Published at http://sergiu121.github.io/refs/pull/15/merge

**Comment by edi33416** [comment]
Am găsit soluția pe baza link-urilor următoare
* https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/WritingReST/MenuHierarchy.html
* https://docs.readthedocs.io/en/stable/guides/adding-custom-css.html

**Comment by Sergiu121** [comment]
Published at http://sergiu121.github.io/refs/pull/15/merge

**Pull request merged**
